# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0
version = 1

[[annotations]]
path = [
 "CHANGELOG.md",
 "notebooks/tablet.livemd",
 "NOTICE",
 "mix.lock",
 "usage-rules.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "assets/*",
 "gallery.md",
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"
